#!/bin/bash

function verbose {
	[ "$VERBOSE" = true ] && echo $1
}

function usage {
	echo "Usage `basename $0` [-c|--config CONFIGFILE] [-e|--list-expires] [-f|--force COMMONNAME] [-n|--no-cert] [-v|--verbose]"
}

function parseopts {
	CONF=`dirname $0`/`basename $0`.cnf
	while [ $# -gt 0 ]; do
		KEY="$1"
		case $KEY in
			-c|--config)
				CONF="$2"
				if [ "$CONF" = "" ]; then
					echo "No CONFIGFILE specified for --config"
					usage
					exit 1
				fi
				shift  # past argument
			;;
			-e|--list-expires)
				LIST_EXPIRES=true
			;;
			-f|--force)
				FORCE="$2"
				if [ "$FORCE" = "" ]; then
					echo "No COMMONNAME specified for --force"
					usage
					exit 1
				fi
				shift  # past argument
			;;
			-v|--verbose)
				VERBOSE=true
			;;
			-n|--no-cert)
				NO_CERT=true
			;;
			*)
				usage
				exit 1
			;;
		esac
		shift
	done
}

function hook {
	: # To be redefined in the config file
}

function loadconf {
	if [ ! -f $CONF ]; then
		echo "Config file $CONF not found"
		exit 2
	fi

	source $CONF

	if [ -z "$EXPIRY_THRESHOLD" ]; then
		echo "EXPIRY_THRESHOLD not defined in $CONF"
		exit 3
	fi

	if [ -z "$CONFDIR" ]; then
		echo "CONFDIR not defined in $CONF"
		exit 3
	fi

	if [ -z "$CERTBOT" ]; then
		echo "CERTBOT not defined in $CONF"
		exit 3
	fi

	if [ -z "$SUBJECT_EMAIL" ]; then
		echo "SUBJECT_EMAIL not defined in $CONF"
		exit 3
	fi
}

function getcert {
	# Build certbot command line and alt names for openssl
	COMMAND=""
	ALT_NAMES=""
	IFS=';' read -a LINES <<<"$DOMAINS"
	for LINE in "${LINES[@]}"; do
		IFS='=' read -a ITEMS <<<"$LINE"
		COMMAND="$COMMAND --webroot-path $WEBROOT_DIR/${ITEMS[0]}"
		IFS=',' read -a DOMAINS <<<"${ITEMS[1]}"
		for DOMAIN in "${DOMAINS[@]}"; do
			COMMAND="$COMMAND --domain $DOMAIN"
			ALT_NAMES="${ALT_NAMES},DNS:$DOMAIN"
		done;
	done
	ALT_NAMES=${ALT_NAMES:1}
	verbose "[$CN$EXT] subject: $SUBJECT"
	verbose "[$CN$EXT] alt_names: $ALT_NAMES"

	OPENSSL_CNF_TEMP=$(mktemp)
	CSR_TEMP=$(mktemp)
	trap "rm -f $OPENSSL_CNF_TEMP $CSR_TEMP" INT TERM HUP EXIT

	# Generate OpenSSL config file
	cat /etc/ssl/openssl.cnf > $OPENSSL_CNF_TEMP
	echo '[ alt_names ]' >> $OPENSSL_CNF_TEMP
	echo "subjectAltName = $ALT_NAMES" >> $OPENSSL_CNF_TEMP

	# Generate CSR
	# Key is owned by root
	sudo openssl req -new -config $OPENSSL_CNF_TEMP -key $PRIVKEY -out $CSR_TEMP -outform der -subj "$SUBJECT" -reqexts alt_names

	# Get the certificate
	verbose "[$CN$EXT] Calling Certbot $CERTBOT with $CERTBOT_EXTRA_OPTS"
	$CERTBOT certonly $CERTBOT_EXTRA_OPTS --csr $CSR_TEMP --cert-path $CERT --chain-path $CHAIN --fullchain-path $FULLCHAIN --webroot $COMMAND

	verbose "[$CN$EXT] Certificate generated $FULLCHAIN_LIVE -> $FULLCHAIN"
	sudo ln --symbolic --force $FULLCHAIN $FULLCHAIN_LIVE

	NEW_CERTS_CN+=($CN)
	NEW_CERTS_EXPIRY+=($(date --date "$(getexpiry $FULLCHAIN_LIVE)" +%s))
}

function getexpiry {
	sudo openssl x509 -in $1 -noout -enddate | sed -n "s/notAfter=//p"
}

function checkexpiry {
	GETCERT=true
	# Certs are owned by root
	if [ "$FORCE" != $CN ] && sudo [ -f $FULLCHAIN_LIVE ]; then
		EXPIRY_DATE=`getexpiry $FULLCHAIN_LIVE`
		verbose "[$CN$EXT] $FULLCHAIN_LIVE already exists and expires $EXPIRY_DATE"
		if [ `expr $NOW_EPOCH + $EXPIRY_THRESHOLD \* 24 \* 60 \* 60` -ge `date --date "$EXPIRY_DATE" +%s` ]; then
			verbose "[$CN$EXT] Certificate expired or expires soon, will be renewed"
			GETCERT=true
		else
			verbose "[$CN$EXT] Certificate will NOT be renewed, expiration date too far"
			GETCERT=false
		fi
	else
		verbose "[$CN$EXT] $FULLCHAIN_LIVE does NOT exist or --force specified"
	fi
	if [ "$GETCERT" = true ]; then
		verbose "[$CN$EXT] Getting certificate"
		if [ "$NO_CERT" != true ]; then
			getcert
			CALLHOOK=true
		else
			verbose "[$CN$EXT] --no-cert specified, skipping"
		fi
	fi
}

function processconf {
	NEW_CERTS_CN=()
	NEW_CERTS_FULLCHAIN=()
	for CONF_FILE in `find $CONFDIR -name \*.cnf | sort`; do
		EXT=""
		source $CONF_FILE
		if [ "$EXT" != "" ]; then
			EXT="-$EXT"
		fi
		NOW=`date --utc +%Y%m%d%H%M%S`
		NOW_EPOCH=`date +%s`
		verbose "[$CN$EXT] Starting at $NOW"

		if sudo [ ! -d $CERT_DIR/archive ]; then
			verbose "[$CN$EXT] Creating directory $CERT_DIR/archive"
			sudo mkdir -p $CERT_DIR/archive
		fi

		CERT=$CERT_DIR/archive/$CN-$NOW.cert$EXT.pem
		CHAIN=$CERT_DIR/archive/$CN-$NOW.chain$EXT.pem
		FULLCHAIN=$CERT_DIR/archive/$CN-$NOW.fullchain$EXT.pem
		FULLCHAIN_LIVE=$CERT_DIR/$CN.fullchain$EXT.pem
		if [ "$LIST_EXPIRES" = true ]; then
			if sudo [ -f $FULLCHAIN_LIVE ]; then
				EXPIRY_DATE=`getexpiry $FULLCHAIN_LIVE`
				DAYS_LEFT=`expr \( $(date -d "$EXPIRY_DATE" +%s) - $NOW_EPOCH \) / 24 / 60 / 60`
				if [ $DAYS_LEFT -le 0 ]; then
					MESSAGE=EXPIRED
				elif [ $DAYS_LEFT = 1 ]; then
					MESSAGE="$DAYS_LEFT DAY"
				else
					MESSAGE="$DAYS_LEFT DAYS"
				fi
				echo "[$CN$EXT] $MESSAGE, $EXPIRY_DATE"
			else
				verbose "[$CN$EXT] $FULLCHAIN_LIVE does NOT exist"
				echo "[$CN$EXT] no certificate found"
			fi
		else
			checkexpiry
		fi
	done
}

function callhook {
	if [ "$CALLHOOK" = true ]; then
		verbose "[common] Calling hook"
		hook
	fi
}

parseopts $@
loadconf
processconf
callhook
